=== Lucascanna/micro-lc/packages/interfaces/schemas/v1/config.schema.json
{
  "$id": "https://cdn.jsdelivr.net/npm/@micro-lc/interfaces@latest/schemas/v1/config.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema",
  "title": "Config",
  "definitions": {
    "internal-plugin": {
      "type": "object",
      "properties": {
        "id": {
          "description": "Unique identifier of the plugin",
          "type": "string"
        },
        "aclExpression": {
          "description": "Expression to evaluate the users that can access the plugin",
          "type": "string"
        },
        "order": {
          "description": "Plugin registration order",
          "type": "integer"
        },
        "integrationMode": {
          "description": "Way in which the plugin is integrated.",
          "type": "string",
          "enum": ["href", "qiankun", "iframe"]
        },
        "pluginRoute": {
          "description": "Path on which the plugin will be rendered",
          "type": "string"
        },
        "pluginUrl": {
          "description": "Entry of the plugin",
          "type": "string"
        },
        "props": {
          "description": "Data passed to the plugin",
          "type": "object",
          "additionalProperties": true
        },
        "externalLink": {
          "type": "object",
          "properties": {
            "url": {
              "description": "Url of the external application",
              "type": "string"
            },
            "sameWindow": {
              "description": "States if the link should be opened in a new window",
              "type": "boolean"
            }
          },
          "additionalProperties": false,
          "required": ["url", "sameWindow"]
        }
      },
      "additionalProperties": false,
      "required": ["id"]
    },

    "plugin": {
      "type": "object",
      "properties": {
        "id": {
          "description": "Unique identifier of the plugin",
          "type": "string"
        },
        "aclExpression": {
          "description": "Expression to evaluate the users that can access the plugin",
          "type": "string"
        },
        "order": {
          "description": "Plugin registration order",
          "type": "integer"
        },
        "integrationMode": {
          "description": "Way in which the plugin is integrated.",
          "type": "string",
          "enum": ["href", "qiankun", "iframe"]
        },
        "pluginRoute": {
          "description": "Path on which the plugin will be rendered",
          "type": "string"
        },
        "pluginUrl": {
          "description": "Entry of the plugin",
          "type": "string"
        },
        "props": {
          "description": "Data passed to the plugin",
          "type": "object",
          "additionalProperties": true
        },
        "externalLink": {
          "type": "object",
          "properties": {
            "url": {
              "description": "Url of the external application",
              "type": "string"
            },
            "sameWindow": {
              "description": "States if the link should be opened in a new window",
              "type": "boolean"
            }
          },
          "additionalProperties": false,
          "required": ["url", "sameWindow"]
        },
        "label": {
          "description": "Label visualized in the side menu",
          "type": "string"
        },
        "icon": {
          "description": "Icon visualized in the side menu",
          "type": "string"
        },
        "category": {
          "description": "Sub-menu category in which insert the plugin",
          "type": "string"
        },
        "content": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/plugin"
          }
        }
      },
      "additionalProperties": false,
      "required": ["id", "label"]
    }
  },
  "type": "object",
  "properties": {
    "theming": {
      "type": "object",
      "properties": {
        "header": {
          "type": "object",
          "properties": {
            "pageTitle": {
              "type": "string"
            },
            "favicon": {
              "type": "string"
            }
          }
        },
        "logo": {
          "type": "object",
          "properties": {
            "url_light_image": {
              "description": "Light logo image url",
              "type": "string"
            },
            "url_dark_image": {
              "description": "Dark logo image url",
              "type": "string"
            },
            "alt": {
              "description": "Logo alt",
              "type": "string"
            },
            "navigation_url": {
              "description": "Link to the navigation page reached when the logo is clicked",
              "type": "string"
            }
          },
          "required": ["url_light_image", "alt"]
        },
        "variables": {
          "type": "object",
          "properties": {
            "primaryColor": {
              "description": "Main theme color",
              "type": "string"
            }
          }
        },
        "menuLocation": {
          "type": "string",
          "default": "sideBar",
          "enum": ["sideBar", "topBar", "fixedSideBar"]
        },
        "enableDarkMode": {
          "type": "boolean",
          "default": false
        }
      },
      "additionalProperties": false,
      "required": ["logo", "variables"]
    },
    "shared": {
      "type": "object",
      "properties": {
        "props": {
          "type": "object"
        }
      }
    },
    "plugins": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/plugin"
      }
    },
    "internalPlugins": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/internal-plugin"
      }
    },
    "analytics": {
      "type": "object",
      "properties": {
        "privacyLink": {
          "description": "Url to the privacy information page",
          "type": "string"
        },
        "disclaimer": {
          "description": "Informative message inside the banner",
          "type": "string"
        },
        "gtmId": {
          "description": "Google tag manager id of the current user needed to instaciate analytics",
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": ["privacyLink", "disclaimer", "gtmId"]
    },
    "helpMenu": {
      "type": "object",
      "properties": {
        "helpLink": {
          "description": "Link to the help page",
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": ["helpLink"]
    },
    "rightMenu": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "entry": {
            "description": "Entry point of the web component",
            "type": "string"
          },
          "tag": {
            "description": "Tag that will be used to mount the web component inside the DOM",
            "type": "string"
          },
          "attributes": {
            "type": "object",
            "additionalProperties": true
          },
          "properties": {
            "type": "object",
            "additionalProperties": true
          }
        },
        "additionalProperties": false,
        "required": ["tag", "entry"]
      }
    }
  }
}

=== Lucascanna/micro-lc/mock-server/api/v1/microlc/configuration/configuration.json
{
  "theming": {
    "header": {
      "pageTitle": "My Company",
      "favicon": "https://www.mia-platform.eu/static/img/favicon/apple-icon-60x60.png"
    },
    "logo": {
      "alt": "My Company",
      "url_light_image": "https://avatars.githubusercontent.com/u/92730708?s=200&v=4",
      "url_dark_image": "https://raw.githubusercontent.com/lauragift21/giftegwuenu.dev/master/src/assets/img/logo-light.png",
      "navigation_url": "https://github.com/micro-lc"
    },
    "variables": {
      "primaryColor": "#4568B5"
    },
    "menuLocation": "topBar"
  },
  "plugins": [
    {
      "id": "plugin-test-2",
      "label": "Href same window",
      "icon": "far fa-window-maximize",
      "order": 2,
      "integrationMode": "href",
      "externalLink": {
        "url": "https://example.com/same-window",
        "sameWindow": true
      }
    }
  ],
  "analytics": {
    "privacyLink": "https://www.mia-platform.eu/img/Privacy_Policy_Website_EN.pdf",
    "disclaimer": "Questo sito utilizza cookie proprietari e di terze parti per assicurarti la migliore esperienza di navigazione. Per ulteriori informazioni, leggi la ",
    "gtmId": "GTM-000000"
  },
  "helpMenu": {
    "helpLink": "https://docs.mia-platform.eu/docs/business_suite/microlc/overview"
  },
  "rightMenu": [{
    "entry": "http://127.0.0.1:8080/wc-entry.esm.js",
    "tag": "wc-tag",
    "attributes": {
      "id": "your-wc-tag"
    }
  }],
  "internalPlugins": [
    {
      "id": "plugin-internal-test-4",
      "order": 5,
      "integrationMode": "iframe",
      "pluginRoute": "/internalPlugin1",
      "pluginUrl": "https://example.com/internal-plugin"
    }
  ]
}

=== Lucascanna/micro-lc/packages/interfaces/schemas/v1/__tests__/test.json
{
  "theming": {
    "header": {
      "pageTitle": "Demo Mia-Backoffice",
      "favicon": "https://www.mia-platform.eu/static/img/favicon/apple-icon-60x60.png"
    },
    "logo": {
      "alt": "Logo",
      "url_light_image": "/public-assets/download/b90e5c79-50b9-4c30-a2fe-00f44233ef55.png"
    },
    "variables": { "primaryColor": "#294C9D" },
    "menuLocation": "fixedSideBar"
  },
  "shared": {
    "props": { "headers": { "client-key": "sYj1FQsWMH1S0wRzvhEpRQ0TuwMnujMj" } }
  },
  "rightMenu": [
    {
      "entry": "/micro-lc-notification-center/micro-lc-notification-center.esm.js",
      "tag": "micro-lc-notification-center",
      "properties": {
        "clickStrategy": "push",
        "limit": 7,
        "mode": "polling",
        "pollingFrequency": 5000,
        "locales": {
          "title": { "it": "Notifiche", "en": "Notifications" },
          "dateFormat": { "it": "DD MMM YYYY", "en": "MMM DD YYYY" },
          "loadingButton": { "it": "Carica altro", "en": "Load more" },
          "errorMessage": {
            "it": "Si Ã¨ verificato un errore, riprovare",
            "en": "An error occurred, try again"
          },
          "noNotification": {
            "it": "Nessuna notifica da visualizzare",
            "en": "No notifications to show"
          },
          "readAll": {
            "it": "Segna tutte come lette",
            "en": "Mark all as read"
          },
          "reload": { "it": "Ricarica", "en": "Reload" },
          "backOnTop": { "it": "Torna all'inizio", "en": "Back on top" }
        }
      }
    }
  ],
  "plugins": [
    {
      "id": "dashboards-analytics",
      "label": "Analytics",
      "icon": "fas fa-chart-bar",
      "integrationMode": "iframe",
      "pluginRoute": "/bo-analytics",
      "pluginUrl": "/data-visualization/#/revenueAndOrdersByDays",
      "props": {}
    },
    {
      "id": "ordersList",
      "label": "Orders",
      "icon": "fas fa-paper-plane",
      "integrationMode": "qiankun",
      "pluginRoute": "/bo-orders-list",
      "pluginUrl": "/element-composer/",
      "props": { "configurationName": "orders-list" }
    },
    {
      "id": "usersCategory",
      "label": "Users",
      "icon": "fas fa-users",
      "content": [
        {
          "id": "ridersList",
          "label": "Riders",
          "icon": "fas fa-biking",
          "integrationMode": "qiankun",
          "pluginRoute": "/bo-riders-list",
          "pluginUrl": "/element-composer/",
          "props": { "configurationName": "riders-list" }
        },
        {
          "id": "ridersShifts",
          "label": "Riders shifts",
          "icon": "fas fa-clipboard-list",
          "integrationMode": "qiankun",
          "pluginRoute": "/bo-riders-shifts",
          "pluginUrl": "/element-composer/",
          "props": { "configurationName": "riders-shift" }
        },
        {
          "id": "customersList",
          "label": "Customers",
          "icon": "fas fa-user-tag",
          "integrationMode": "qiankun",
          "pluginRoute": "/bo-customers-list",
          "pluginUrl": "/element-composer/",
          "props": { "configurationName": "customers-list" }
        }
      ]
    },
    {
      "id": "menuCategory",
      "label": "Menu",
      "icon": "fas fa-book-open",
      "content": [
        {
          "id": "dishesList",
          "label": "Dishes",
          "icon": "fas fa-utensils",
          "integrationMode": "qiankun",
          "pluginRoute": "/bo-dishes-list",
          "pluginUrl": "/element-composer/",
          "props": { "configurationName": "dishes-list" }
        },
        {
          "id": "ingredientsList",
          "label": "Ingredients",
          "icon": "fas fa-fish",
          "integrationMode": "qiankun",
          "pluginRoute": "/bo-ingredients-list",
          "pluginUrl": "/element-composer/",
          "props": { "configurationName": "ingredients-list" }
        }
      ]
    },
    {
      "id": "restaurantsList",
      "label": "Restaurants",
      "icon": "fas fa-store",
      "integrationMode": "qiankun",
      "pluginRoute": "/bo-restaurants-list",
      "pluginUrl": "/element-composer/",
      "props": { "configurationName": "restaurants-list" }
    },
    {
      "id": "user-collections",
      "label": "User Collections",
      "icon": "fas fa-user",
      "integrationMode": "qiankun",
      "pluginRoute": "/bo-users-collections",
      "pluginUrl": "/element-composer/",
      "props": { "configurationName": "user-collections" }
    }
  ],
  "internalPlugins": [
    {
      "id": "restaurant-details",
      "order": 0,
      "integrationMode": "qiankun",
      "pluginRoute": "/bo-restaurant-details",
      "pluginUrl": "/element-composer/",
      "props": { "configurationName": "restaurant-details" }
    }
  ]
}
